services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /home/sergey/apps/home_assistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    ports:
      # The HTTP port
      - "80:80"
    privileged: true
    network_mode: host