networks:
  web:
    external: true

services:
  home-assistant:
    container_name: home-assistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /home/sergey/apps/home_assistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    networks:
     - "web"
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_BIND_SERVICE
      - SYS_ADMIN
    labels:
      - "traefik.http.routers.home-assistant.rule=Host(`ha.media-server.local`)"
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.services.home-assistant.loadbalancer.server.port=8123"