networks:
  web:
    address: ":80"

services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /home/sergey/apps/home_assistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    networks:
     - "web"
    network_mode: host
    labels:
      - "traefik.http.routers.home-assistant.rule=Host(`ha.media-server.local`)"
      - "traefik.enable=true"